### ISSUE TITLE
CSS minification is broken

### ISSUE THREAD

**Issue by jez** [ZachSaucier/Just-Read#126]
https://github.com/ZachSaucier/Just-Read/blob/0444083b8e3cd1b88c5fb48bc18bb4debc5a054b/options.js#L373-L376

Minifying CSS like this doesn't work. For example:

```css
p {
  margin: 0 auto;
}
```

becomes

```css
p{margin:0auto;}
```

The string `0auto` is not a valid setting for `margin`.

I'd recommend using a dedicated library for this, as it's going to be **much** more reliable than doing it yourself.
