### ISSUE TITLE
Can you add the current domain name as a container class so we can have site-specific css hacks?

### ISSUE THREAD

**Issue by nkmathew** [ZachSaucier/Just-Read#288]
**Is your feature request related to a problem? Please describe.**

JustRead does a decent job of extracting text content from pages but sometimes you get some site specific markup/styling getting in the way, e.g a banner or header that shows up together with the article. While you can use CSS to block this `.header { display:none }` it'll end up hiding content that you could've wanted to see on other sites that ended up having the same css class names.

**Describe the solution you'd like**

If the site is `tangowithdjango.com` convert the domain and tld to a 'slug' e.g `tangowithdjango_com` and add it to `simple-container`:

```html
<div class="simple-container tangowithdjango_com">

....

</div>

```

The css hack would look like:

```css

.tangowithdjango_com div.highlight,
.tangowithdjango_com div.highlight-guess,
.tangowithdjango_com div.highlight-python {
  padding-left: 1em;
  font-size: 80%;
}

 ```

Makes the css more maintainable if you're someone who's obsessed with tinkering every site till it looks ideal without little annoying elements looking out place
