### ISSUE TITLE
Content is blank if the domain contains various words

### ISSUE THREAD

**Issue by iandunn** [ZachSaucier/Just-Read#357]
### To Reproduce

1. Visit a site with `search` in the domain name, like https://www.researchgate.net/publication/319583707_F4-1_Are_curved_displays_ergonomically_advantageous_over_flat_displays_Some_positive_results_from_three_display_curvature_studies_on_monitors_and_TVs
2. Open Just Read

### Expected behavior
The article content should be shown

### Actual behavior
The screen is blank, because `<body class="www-researchgate-net simple-compact-view">` matches the following injected CSS:

```css
[class *= "navigation"], [class *= "nav"], nav, [class *= "search"], [class *= "menu"], [class *= "print"]:not(.simple-print) {
    display: none;
}
```

### Potential Solution

Add this to the default stylesheet:

```css
body {
    display: block !important;
}
```

**Comment by ZachSaucier** [comment]
Hey Ian, thanks for posting. 

This is due to the "Use hide-segments.css" feature. If you go to Just Read's options you can un-check this functionality to disable it. Usually there's not much I can do besides share that information (or greatly degrade Just Read's ability to filter unrelated content _within_ the article). 

But in this case I can add an exception for classes containing `research` by using `[class *= "search"]:not([class *= "research"])`. I'll do that in the next version.

**Comment by iandunn** [comment]
Ah, I see, thanks!

There's going to be thousands of false-positive matches, though, so it doesn't feel like simply excluding `research` will really make a meaningful difference.

What do you think about modifying the rule to only target elements that are _children_ of `body`? That'd avoid all false-positives related to domain names. e.g.,

```css
body > [class *= "navigation"] {
    display: none;
}
```
